apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-arduino-agent
spec:
  containers:
  - name: arduino-cli
    image: your-registry/arduino-cli-agent:latest
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: "512Mi"
        cpu: "0.5"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  volumes:
  - name: workspace-volume
    emptyDir: {}
